-- SEO article seed for BoomLaLaBoom (FR/EN/ES)
insert into public.articles (
  slug_fr, slug_en, slug_es,
  title_fr, title_en, title_es,
  excerpt_fr, excerpt_en, excerpt_es,
  content_fr, content_en, content_es,
  thumbnail_url, author_name, read_time_minutes, is_featured, published_at,
  meta_title_fr, meta_title_en, meta_title_es,
  meta_description_fr, meta_description_en, meta_description_es
) values
(
  'comptines-pour-dormir',
  'bedtime-nursery-rhymes',
  'canciones-para-dormir',
  'Comptines pour dormir: calmer et rassurer',
  'Bedtime nursery rhymes: calm and comfort',
  'Canciones para dormir: calma y consuelo',
  'Des comptines douces pour aider les enfants a se detendre avant le dodo.',
  'Soft rhymes to help kids relax before bedtime.',
  'Canciones suaves para ayudar a los ninos a relajarse antes de dormir.',
  '<h2>Pourquoi les comptines du soir aident</h2><p>Les chansons lentes apaisent et creent un rituel securisant.</p><h2>Idees de playlist</h2><ul><li>Berceuses lentes</li><li>Comptines repetitives</li><li>Chants en chuchotant</li></ul><h2>Conseils parents</h2><p>Garder le meme ordre chaque soir.</p>',
  '<h2>Why bedtime rhymes help</h2><p>Slow songs calm children and build a safe routine.</p><h2>Playlist ideas</h2><ul><li>Soft lullabies</li><li>Repetitive rhymes</li><li>Whispered songs</li></ul><h2>Parent tips</h2><p>Keep the same order each night.</p>',
  '<h2>Por que ayudan las canciones</h2><p>Las canciones lentas calman y crean una rutina segura.</p><h2>Ideas de lista</h2><ul><li>Nanas suaves</li><li>Rimas repetitivas</li><li>Canciones susurradas</li></ul><h2>Consejos</h2><p>Mantener el mismo orden cada noche.</p>',
  '',
  'BoomLaLaBoom Team',
  4,
  false,
  now(),
  'Comptines pour dormir pour enfants',
  'Bedtime nursery rhymes for kids',
  'Canciones para dormir para ninos',
  'Comptines douces pour le coucher et un sommeil calme.',
  'Soft bedtime rhymes for a calm sleep routine.',
  'Canciones suaves para una rutina de sueno tranquila.'
),
(
  'chansons-couleurs',
  'songs-to-learn-colors',
  'canciones-para-colores',
  'Chansons pour apprendre les couleurs',
  'Songs to learn colors',
  'Canciones para aprender colores',
  'Apprendre les couleurs avec des chansons courtes et ludiques.',
  'Learn colors with short and playful songs.',
  'Aprende colores con canciones cortas y divertidas.',
  '<h2>Couleurs et memoire</h2><p>Associer une couleur a une melodie aide la memoire.</p><h2>Exemples de jeux</h2><ul><li>Montrer un objet</li><li>Nommer la couleur</li><li>Repeter en chanson</li></ul>',
  '<h2>Colors and memory</h2><p>Matching a color to a melody helps memory.</p><h2>Game ideas</h2><ul><li>Show an object</li><li>Name the color</li><li>Repeat in song</li></ul>',
  '<h2>Colores y memoria</h2><p>Unir color y melodia ayuda a recordar.</p><h2>Juegos</h2><ul><li>Mostrar un objeto</li><li>Nombrar el color</li><li>Repetir cantando</li></ul>',
  '',
  'BoomLaLaBoom Team',
  4,
  false,
  now() - interval '1 day',
  'Chansons pour apprendre les couleurs',
  'Songs to learn colors',
  'Canciones para aprender colores',
  'Comptines et jeux musicaux pour reconnaitre les couleurs.',
  'Songs and games to recognize colors.',
  'Canciones y juegos para reconocer colores.'
),
(
  'comptines-nombres',
  'counting-songs-for-kids',
  'canciones-para-contar',
  'Comptines pour apprendre les nombres',
  'Counting songs for kids',
  'Canciones para aprender numeros',
  'Compter en musique aide les enfants a memoriser les nombres.',
  'Counting in music helps kids remember numbers.',
  'Contar con musica ayuda a recordar los numeros.',
  '<h2>Pourquoi la musique aide</h2><p>Le rythme facilite la repetition des nombres.</p><h2>Idees</h2><ul><li>Comptines 1 a 10</li><li>Jeux de doigts</li><li>Ritmes de pas</li></ul>',
  '<h2>Why music helps</h2><p>Rhythm makes number repetition easier.</p><h2>Ideas</h2><ul><li>Songs 1 to 10</li><li>Finger games</li><li>Step rhythms</li></ul>',
  '<h2>Por que ayuda la musica</h2><p>El ritmo facilita repetir numeros.</p><h2>Ideas</h2><ul><li>Canciones 1 a 10</li><li>Juegos de dedos</li><li>Ritmo con pasos</li></ul>',
  '',
  'BoomLaLaBoom Team',
  4,
  false,
  now() - interval '2 days',
  'Comptines pour apprendre les nombres',
  'Counting songs for kids',
  'Canciones para aprender numeros',
  'Chansons et jeux de comptage pour enfants.',
  'Counting songs and games for kids.',
  'Canciones y juegos de conteo para ninos.'
),
(
  'comptines-anglais',
  'english-songs-for-kids',
  'canciones-ingles',
  'Comptines en anglais pour enfants',
  'English songs for kids',
  'Canciones en ingles para ninos',
  'Des comptines simples pour decouvrir les premiers mots anglais.',
  'Simple songs to discover first English words.',
  'Canciones simples para descubrir primeras palabras en ingles.',
  '<h2>Debuter en anglais</h2><p>Commencer par des mots courts et repetitifs.</p><h2>Idees</h2><ul><li>Hello songs</li><li>Colors</li><li>Animals</li></ul>',
  '<h2>Start in English</h2><p>Begin with short and repetitive words.</p><h2>Ideas</h2><ul><li>Hello songs</li><li>Colors</li><li>Animals</li></ul>',
  '<h2>Empezar en ingles</h2><p>Empezar con palabras cortas y repetitivas.</p><h2>Ideas</h2><ul><li>Saludos</li><li>Colores</li><li>Animales</li></ul>',
  '',
  'BoomLaLaBoom Team',
  4,
  false,
  now() - interval '3 days',
  'Comptines en anglais pour enfants',
  'English songs for kids',
  'Canciones en ingles para ninos',
  'Chansons faciles pour apprendre l anglais en musique.',
  'Easy songs to learn English with music.',
  'Canciones faciles para aprender ingles con musica.'
),
(
  'comptines-espagnol',
  'spanish-songs-for-kids',
  'canciones-espanol',
  'Comptines en espagnol pour enfants',
  'Spanish songs for kids',
  'Canciones en espanol para ninos',
  'Apprendre l espagnol avec des chansons courtes et joyeuses.',
  'Learn Spanish with short and joyful songs.',
  'Aprende espanol con canciones cortas y alegres.',
  '<h2>Premiers mots</h2><p>Les refrains repetes aident la prononciation.</p><h2>Idees</h2><ul><li>Bonjour</li><li>Couleurs</li><li>Animaux</li></ul>',
  '<h2>First words</h2><p>Repeated choruses help pronunciation.</p><h2>Ideas</h2><ul><li>Hello</li><li>Colors</li><li>Animals</li></ul>',
  '<h2>Primeras palabras</h2><p>Los coros repetidos ayudan la pronunciacion.</p><h2>Ideas</h2><ul><li>Hola</li><li>Colores</li><li>Animales</li></ul>',
  '',
  'BoomLaLaBoom Team',
  4,
  false,
  now() - interval '4 days',
  'Comptines en espagnol pour enfants',
  'Spanish songs for kids',
  'Canciones en espanol para ninos',
  'Comptines simples pour decouvrir l espagnol.',
  'Simple songs to discover Spanish.',
  'Canciones simples para descubrir espanol.'
),
(
  'comptines-ferme',
  'farm-nursery-rhymes',
  'canciones-granja',
  'Comptines de la ferme pour enfants',
  'Farm nursery rhymes',
  'Canciones de la granja',
  'Des chansons sur les animaux de la ferme pour apprendre en s amusant.',
  'Songs about farm animals to learn with fun.',
  'Canciones sobre animales de granja para aprender jugando.',
  '<h2>Animaux de la ferme</h2><p>Vache, mouton, cheval et cochon chantent.</p><h2>Jeux</h2><ul><li>Imiter les sons</li><li>Nommer les animaux</li><li>Danser en rond</li></ul>',
  '<h2>Farm animals</h2><p>Cow, sheep, horse, and pig sing.</p><h2>Games</h2><ul><li>Imitate sounds</li><li>Name animals</li><li>Circle dance</li></ul>',
  '<h2>Animales de granja</h2><p>Vaca, oveja, caballo y cerdo cantan.</p><h2>Juegos</h2><ul><li>Imitar sonidos</li><li>Nombrar animales</li><li>Bailar en ronda</li></ul>',
  '',
  'BoomLaLaBoom Team',
  4,
  false,
  now() - interval '5 days',
  'Comptines de la ferme',
  'Farm nursery rhymes',
  'Canciones de la granja',
  'Chansons sur les animaux de la ferme pour enfants.',
  'Songs about farm animals for kids.',
  'Canciones sobre animales de granja para ninos.'
),
(
  'comptines-emotions',
  'songs-about-feelings',
  'canciones-emociones',
  'Chansons pour parler des emotions',
  'Songs about feelings',
  'Canciones sobre emociones',
  'Des chansons pour aider les enfants a exprimer leurs emotions.',
  'Songs that help kids express feelings.',
  'Canciones que ayudan a expresar emociones.',
  '<h2>Nommer les emotions</h2><p>Joie, peur, colere et calme en musique.</p><h2>Activites</h2><ul><li>Mimer les emotions</li><li>Choisir une couleur</li><li>Chanter ensemble</li></ul>',
  '<h2>Name the feelings</h2><p>Joy, fear, anger, and calm in music.</p><h2>Activities</h2><ul><li>Act out feelings</li><li>Pick a color</li><li>Sing together</li></ul>',
  '<h2>Nombrar emociones</h2><p>Alegria, miedo, enojo y calma con musica.</p><h2>Actividades</h2><ul><li>Imitar emociones</li><li>Elegir color</li><li>Cantar juntos</li></ul>',
  '',
  'BoomLaLaBoom Team',
  4,
  false,
  now() - interval '6 days',
  'Chansons pour les emotions',
  'Songs about feelings',
  'Canciones sobre emociones',
  'Comptines pour aider les enfants a exprimer leurs emotions.',
  'Rhymes to help kids express feelings.',
  'Canciones para ayudar a expresar emociones.'
),
(
  'comptines-formes',
  'songs-to-learn-shapes',
  'canciones-formas',
  'Comptines pour apprendre les formes',
  'Songs to learn shapes',
  'Canciones para aprender formas',
  'Apprendre les formes avec des chansons et des jeux.',
  'Learn shapes with songs and games.',
  'Aprende formas con canciones y juegos.',
  '<h2>Formes et musique</h2><p>Cercle, carre, triangle en rythme.</p><h2>Jeux</h2><ul><li>Tracer dans l air</li><li>Montrer des objets</li><li>Repetition chantee</li></ul>',
  '<h2>Shapes and music</h2><p>Circle, square, triangle in rhythm.</p><h2>Games</h2><ul><li>Trace in the air</li><li>Show objects</li><li>Sung repetition</li></ul>',
  '<h2>Formas y musica</h2><p>Circulo, cuadrado, triangulo con ritmo.</p><h2>Juegos</h2><ul><li>Trazar en el aire</li><li>Mostrar objetos</li><li>Repetir cantando</li></ul>',
  '',
  'BoomLaLaBoom Team',
  4,
  false,
  now() - interval '7 days',
  'Comptines pour apprendre les formes',
  'Songs to learn shapes',
  'Canciones para aprender formas',
  'Chansons pour reconnaitre les formes avec les enfants.',
  'Songs to recognize shapes with kids.',
  'Canciones para reconocer formas con ninos.'
),
(
  'comptines-animaux',
  'songs-about-animals',
  'canciones-animales',
  'Chansons pour apprendre les animaux',
  'Songs about animals',
  'Canciones sobre animales',
  'Les animaux en chanson pour enrichir le vocabulaire.',
  'Animals in songs to enrich vocabulary.',
  'Animales en canciones para ampliar vocabulario.',
  '<h2>Nommer les animaux</h2><p>Associer un son a un animal aide a retenir.</p><h2>Idees</h2><ul><li>Imiter les cris</li><li>Cartes imagées</li><li>Comptines courtes</li></ul>',
  '<h2>Name the animals</h2><p>Matching sounds to animals helps memory.</p><h2>Ideas</h2><ul><li>Imitate sounds</li><li>Picture cards</li><li>Short rhymes</li></ul>',
  '<h2>Nombrar animales</h2><p>Asociar sonido y animal ayuda a recordar.</p><h2>Ideas</h2><ul><li>Imitar sonidos</li><li>Tarjetas con imagen</li><li>Rimas cortas</li></ul>',
  '',
  'BoomLaLaBoom Team',
  4,
  false,
  now() - interval '8 days',
  'Chansons sur les animaux',
  'Songs about animals',
  'Canciones sobre animales',
  'Comptines pour apprendre les animaux en musique.',
  'Songs to learn animals with music.',
  'Canciones para aprender animales con musica.'
),
(
  'jeux-rythme',
  'rhythm-games-for-kids',
  'juegos-ritmo',
  'Jeux de rythme pour enfants',
  'Rhythm games for kids',
  'Juegos de ritmo para ninos',
  'Des jeux simples pour taper en rythme et bouger.',
  'Simple games to tap rhythms and move.',
  'Juegos simples para marcar ritmo y moverse.',
  '<h2>Pourquoi le rythme</h2><p>Le rythme aide la coordination et l ecoute.</p><h2>Idees</h2><ul><li>Clap clap</li><li>Marcher en cadence</li><li>Suivre la musique</li></ul>',
  '<h2>Why rhythm</h2><p>Rhythm helps coordination and listening.</p><h2>Ideas</h2><ul><li>Clap clap</li><li>Walk in tempo</li><li>Follow the music</li></ul>',
  '<h2>Por que el ritmo</h2><p>El ritmo ayuda coordinacion y escucha.</p><h2>Ideas</h2><ul><li>Palmas</li><li>Caminar al compas</li><li>Seguir la musica</li></ul>',
  '',
  'BoomLaLaBoom Team',
  4,
  false,
  now() - interval '9 days',
  'Jeux de rythme pour enfants',
  'Rhythm games for kids',
  'Juegos de ritmo para ninos',
  'Activites musicales pour bouger en rythme.',
  'Music activities to move in rhythm.',
  'Actividades musicales para moverse con ritmo.'
),
(
  'jeux-memoire',
  'memory-games-for-kids',
  'juegos-memoria',
  'Jeux de memoire pour enfants',
  'Memory games for kids',
  'Juegos de memoria para ninos',
  'Des jeux de cartes et d images pour entrainer la memoire.',
  'Card and picture games to train memory.',
  'Juegos de cartas e imagenes para entrenar memoria.',
  '<h2>Pourquoi jouer</h2><p>La memoire se renforce avec la repetition.</p><h2>Idees</h2><ul><li>Paires d images</li><li>Ordre des couleurs</li><li>Chansons a repondre</li></ul>',
  '<h2>Why play</h2><p>Memory grows with repetition.</p><h2>Ideas</h2><ul><li>Picture pairs</li><li>Color order</li><li>Call and response</li></ul>',
  '<h2>Por que jugar</h2><p>La memoria crece con la repeticion.</p><h2>Ideas</h2><ul><li>Parejas de imagenes</li><li>Orden de colores</li><li>Respuesta musical</li></ul>',
  '',
  'BoomLaLaBoom Team',
  4,
  false,
  now() - interval '10 days',
  'Jeux de memoire pour enfants',
  'Memory games for kids',
  'Juegos de memoria para ninos',
  'Jeux pour travailler la memoire en s amusant.',
  'Games to train memory with fun.',
  'Juegos para entrenar memoria con diversion.'
),
(
  'rituels-du-bain',
  'bath-time-songs',
  'canciones-bano',
  'Chansons pour le bain',
  'Bath time songs',
  'Canciones para el bano',
  'Des chansons pour rendre le bain joyeux et calme.',
  'Songs to make bath time fun and calm.',
  'Canciones para un bano divertido y tranquilo.',
  '<h2>Rituel du bain</h2><p>La musique aide a transformer le bain en jeu.</p><h2>Idees</h2><ul><li>Chanson de bulles</li><li>Comptine des mains</li><li>Rincons a chanter</li></ul>',
  '<h2>Bath routine</h2><p>Music turns bath time into play.</p><h2>Ideas</h2><ul><li>Bubbles song</li><li>Hand washing rhyme</li><li>Splashy chorus</li></ul>',
  '<h2>Rutina del bano</h2><p>La musica convierte el bano en juego.</p><h2>Ideas</h2><ul><li>Cancion de burbujas</li><li>Rima de manos</li><li>Estribillos</li></ul>',
  '',
  'BoomLaLaBoom Team',
  4,
  false,
  now() - interval '11 days',
  'Chansons pour le bain enfants',
  'Bath time songs for kids',
  'Canciones para el bano de ninos',
  'Comptines pour un bain doux et amusant.',
  'Songs for a gentle and fun bath.',
  'Canciones para un bano suave y divertido.'
),
(
  'chansons-rangement',
  'tidy-up-songs',
  'canciones-ordenar',
  'Chansons pour le rangement',
  'Tidy up songs',
  'Canciones para ordenar',
  'Des chansons courtes pour ranger en s amusant.',
  'Short songs to tidy up with fun.',
  'Canciones cortas para ordenar con diversion.',
  '<h2>Ranger en musique</h2><p>Un refrain simple encourage les enfants.</p><h2>Astuce</h2><p>Utiliser la meme chanson chaque jour.</p>',
  '<h2>Tidy with music</h2><p>A simple chorus motivates kids.</p><h2>Tip</h2><p>Use the same song daily.</p>',
  '<h2>Ordenar con musica</h2><p>Un estribillo simple motiva.</p><h2>Consejo</h2><p>Usar la misma cancion cada dia.</p>',
  '',
  'BoomLaLaBoom Team',
  3,
  false,
  now() - interval '12 days',
  'Chansons pour le rangement enfants',
  'Tidy up songs for kids',
  'Canciones para ordenar ninos',
  'Comptines pour aider a ranger sans stress.',
  'Songs to help kids tidy without stress.',
  'Canciones para ordenar sin estres.'
),
(
  'comptines-maternelle',
  'preschool-nursery-rhymes',
  'canciones-preescolar',
  'Comptines pour la maternelle',
  'Preschool nursery rhymes',
  'Canciones para preescolar',
  'Des comptines adaptees aux enfants de maternelle.',
  'Rhymes suited for preschool kids.',
  'Rimas adaptadas a preescolar.',
  '<h2>Objectifs</h2><p>Langage, rythme et coordination.</p><h2>Formats</h2><ul><li>Chansons courtes</li><li>Gestes simples</li><li>Refrains repetes</li></ul>',
  '<h2>Goals</h2><p>Language, rhythm, and coordination.</p><h2>Formats</h2><ul><li>Short songs</li><li>Simple gestures</li><li>Repeated chorus</li></ul>',
  '<h2>Objetivos</h2><p>Lenguaje, ritmo y coordinacion.</p><h2>Formatos</h2><ul><li>Canciones cortas</li><li>Gestos simples</li><li>Refranes repetidos</li></ul>',
  '',
  'BoomLaLaBoom Team',
  4,
  false,
  now() - interval '13 days',
  'Comptines pour la maternelle',
  'Preschool nursery rhymes',
  'Canciones para preescolar',
  'Comptines pour apprendre en maternelle.',
  'Rhymes to learn in preschool.',
  'Rimas para aprender en preescolar.'
),
(
  'comptines-motricite',
  'movement-songs-for-kids',
  'canciones-movimiento',
  'Chansons pour bouger',
  'Movement songs for kids',
  'Canciones para moverse',
  'Des chansons pour danser et bouger en rythme.',
  'Songs to dance and move in rhythm.',
  'Canciones para bailar y moverse.',
  '<h2>Pourquoi bouger</h2><p>Le mouvement aide la coordination.</p><h2>Jeux</h2><ul><li>Sauter</li><li>Tourner</li><li>Marcher vite</li></ul>',
  '<h2>Why move</h2><p>Movement improves coordination.</p><h2>Games</h2><ul><li>Jump</li><li>Spin</li><li>Fast walk</li></ul>',
  '<h2>Por que moverse</h2><p>El movimiento mejora la coordinacion.</p><h2>Juegos</h2><ul><li>Saltar</li><li>Girar</li><li>Caminar rapido</li></ul>',
  '',
  'BoomLaLaBoom Team',
  4,
  false,
  now() - interval '14 days',
  'Chansons pour bouger enfants',
  'Movement songs for kids',
  'Canciones para moverse ninos',
  'Comptines dynamiques pour faire bouger les enfants.',
  'Dynamic songs to get kids moving.',
  'Canciones dinamicas para mover a los ninos.'
),
(
  'jeux-coordination',
  'coordination-games',
  'juegos-coordinacion',
  'Jeux de coordination',
  'Coordination games',
  'Juegos de coordinacion',
  'Des jeux simples pour developper la coordination.',
  'Simple games to develop coordination.',
  'Juegos simples para desarrollar coordinacion.',
  '<h2>Idees</h2><ul><li>Taper des mains</li><li>Suivre un rythme</li><li>Changer de vitesse</li></ul>',
  '<h2>Ideas</h2><ul><li>Clap hands</li><li>Follow a rhythm</li><li>Change speed</li></ul>',
  '<h2>Ideas</h2><ul><li>Aplaudir</li><li>Seguir un ritmo</li><li>Cambiar velocidad</li></ul>',
  '',
  'BoomLaLaBoom Team',
  3,
  false,
  now() - interval '15 days',
  'Jeux de coordination pour enfants',
  'Coordination games for kids',
  'Juegos de coordinacion para ninos',
  'Activites ludiques pour coordonner gestes et rythme.',
  'Playful activities for coordination and rhythm.',
  'Actividades para coordinar gestos y ritmo.'
),
(
  'histoires-musicales',
  'musical-stories-for-kids',
  'historias-musicales',
  'Histoires musicales pour enfants',
  'Musical stories for kids',
  'Historias musicales para ninos',
  'Des histoires courtes avec des chansons pour captiver.',
  'Short stories with songs to engage kids.',
  'Historias cortas con canciones para atraer.',
  '<h2>Pourquoi ca marche</h2><p>Le recit aide a garder l attention.</p><h2>Astuce</h2><p>Utiliser des refrains.</p>',
  '<h2>Why it works</h2><p>Storytelling keeps attention.</p><h2>Tip</h2><p>Use short choruses.</p>',
  '<h2>Por que funciona</h2><p>El relato mantiene la atencion.</p><h2>Consejo</h2><p>Usar coros cortos.</p>',
  '',
  'BoomLaLaBoom Team',
  4,
  false,
  now() - interval '16 days',
  'Histoires musicales pour enfants',
  'Musical stories for kids',
  'Historias musicales para ninos',
  'Histoires et chansons pour apprendre en s amusant.',
  'Stories and songs to learn with fun.',
  'Historias y canciones para aprender jugando.'
),
(
  'comptines-rituels-matin',
  'morning-routine-songs',
  'canciones-rutina-manana',
  'Chansons pour le rituel du matin',
  'Morning routine songs',
  'Canciones para rutina de manana',
  'Des chansons pour demarrer la journee avec energie.',
  'Songs to start the day with energy.',
  'Canciones para empezar el dia con energia.',
  '<h2>Rituel du matin</h2><p>Une chanson pour se lever, une pour se preparer.</p>',
  '<h2>Morning routine</h2><p>One song to wake up, one to get ready.</p>',
  '<h2>Rutina de manana</h2><p>Una cancion para levantarse, otra para prepararse.</p>',
  '',
  'BoomLaLaBoom Team',
  3,
  false,
  now() - interval '17 days',
  'Chansons pour rituel du matin',
  'Morning routine songs for kids',
  'Canciones para rutina de manana',
  'Comptines pour demarrer la journee sereinement.',
  'Songs to start the day smoothly.',
  'Canciones para empezar el dia con calma.'
),
(
  'chansons-siestes',
  'nap-time-songs',
  'canciones-siesta',
  'Chansons pour la sieste',
  'Nap time songs',
  'Canciones para la siesta',
  'Des chansons calmes pour la sieste des petits.',
  'Calm songs for nap time.',
  'Canciones calmadas para la siesta.',
  '<h2>Ambiance douce</h2><p>Le tempo lent favorise la relaxation.</p>',
  '<h2>Soft mood</h2><p>Slow tempo supports relaxation.</p>',
  '<h2>Ambiente suave</h2><p>El tempo lento ayuda a relajarse.</p>',
  '',
  'BoomLaLaBoom Team',
  3,
  false,
  now() - interval '18 days',
  'Chansons pour la sieste',
  'Nap time songs',
  'Canciones para la siesta',
  'Comptines douces pour aider a la sieste.',
  'Soft rhymes for nap time.',
  'Rimas suaves para la siesta.'
),
(
  'apprendre-alphabet',
  'alphabet-songs-for-kids',
  'canciones-alfabeto',
  'Chansons pour apprendre l alphabet',
  'Alphabet songs for kids',
  'Canciones del alfabeto',
  'Des chansons pour memoriser les lettres.',
  'Songs to memorize letters.',
  'Canciones para memorizar letras.',
  '<h2>Alphabet en musique</h2><p>Les lettres avec un rythme simple.</p>',
  '<h2>Alphabet with music</h2><p>Letters with a simple rhythm.</p>',
  '<h2>Alfabeto con musica</h2><p>Letras con un ritmo simple.</p>',
  '',
  'BoomLaLaBoom Team',
  4,
  false,
  now() - interval '19 days',
  'Chansons alphabet pour enfants',
  'Alphabet songs for kids',
  'Canciones del alfabeto para ninos',
  'Comptines pour apprendre les lettres en musique.',
  'Songs to learn letters with music.',
  'Canciones para aprender letras con musica.'
),
(
  'top-10-comptines',
  'top-10-nursery-rhymes',
  'top-10-canciones',
  'Top 10 des comptines',
  'Top 10 nursery rhymes',
  'Top 10 canciones',
  'Selection des comptines preferees des enfants.',
  'Selection of favorite rhymes for kids.',
  'Seleccion de canciones favoritas de ninos.',
  '<h2>Notre selection</h2><p>Des comptines qui plaisent aux enfants.</p>',
  '<h2>Our selection</h2><p>Rhymes kids love the most.</p>',
  '<h2>Nuestra seleccion</h2><p>Canciones que encantan a los ninos.</p>',
  '',
  'BoomLaLaBoom Team',
  5,
  false,
  now() - interval '20 days',
  'Top 10 comptines pour enfants',
  'Top 10 nursery rhymes for kids',
  'Top 10 canciones para ninos',
  'Decouvrez les comptines preferees des familles.',
  'Discover the favorite rhymes of families.',
  'Descubre las canciones favoritas de las familias.'
),
(
  'conseils-parents-musique',
  'parent-tips-music-learning',
  'consejos-padres-musica',
  'Conseils parents pour apprendre en musique',
  'Parent tips for music learning',
  'Consejos para aprender con musica',
  'Conseils simples pour accompagner les enfants avec la musique.',
  'Simple tips to support kids with music.',
  'Consejos simples para apoyar con musica.',
  '<h2>Routines</h2><p>Une chanson par moment cle de la journee.</p><h2>Participation</h2><p>Chanter ensemble renforce la confiance.</p>',
  '<h2>Routines</h2><p>One song for each key moment.</p><h2>Participation</h2><p>Sing together to build confidence.</p>',
  '<h2>Rutinas</h2><p>Una cancion por momento clave.</p><h2>Participacion</h2><p>Cantar juntos refuerza la confianza.</p>',
  '',
  'BoomLaLaBoom Team',
  4,
  false,
  now() - interval '21 days',
  'Conseils parents et musique',
  'Parent tips and music',
  'Consejos para padres y musica',
  'Astuces pour apprendre en musique au quotidien.',
  'Tips to learn with music daily.',
  'Consejos para aprender con musica cada dia.'
),
(
  'activites-imprimables',
  'printable-activities-kids',
  'actividades-imprimibles',
  'Activites imprimables pour enfants',
  'Printable activities for kids',
  'Actividades imprimibles para ninos',
  'Des fiches simples pour jouer et apprendre a la maison.',
  'Simple sheets to play and learn at home.',
  'Fichas simples para jugar y aprender en casa.',
  '<h2>Pourquoi imprimer</h2><p>Les activites papier sont calmes et utiles.</p><h2>Idees</h2><ul><li>Coloriages</li><li>Cartes de vocabulaire</li><li>Jeux de memoire</li></ul>',
  '<h2>Why print</h2><p>Paper activities are calm and useful.</p><h2>Ideas</h2><ul><li>Coloring</li><li>Vocabulary cards</li><li>Memory games</li></ul>',
  '<h2>Por que imprimir</h2><p>Actividades en papel son calmadas y utiles.</p><h2>Ideas</h2><ul><li>Colorear</li><li>Tarjetas de vocabulario</li><li>Juegos de memoria</li></ul>',
  '',
  'BoomLaLaBoom Team',
  5,
  false,
  now() - interval '22 days',
  'Activites imprimables enfants',
  'Printable activities for kids',
  'Actividades imprimibles para ninos',
  'Fiches simples pour apprendre a la maison.',
  'Simple worksheets to learn at home.',
  'Fichas simples para aprender en casa.'
),
(
  'chansons-langage',
  'music-and-language-development',
  'musica-y-lenguaje',
  'Musique et developpement du langage',
  'Music and language development',
  'Musica y desarrollo del lenguaje',
  'La musique aide le langage et la prononciation.',
  'Music supports language and pronunciation.',
  'La musica apoya el lenguaje y la pronunciacion.',
  '<h2>Benefices</h2><p>Repetition, rythme et ecoute active.</p><h2>Conseil</h2><p>Repeter chaque jour.</p>',
  '<h2>Benefits</h2><p>Repetition, rhythm, and active listening.</p><h2>Tip</h2><p>Repeat daily.</p>',
  '<h2>Beneficios</h2><p>Repeticion, ritmo y escucha.</p><h2>Consejo</h2><p>Repetir cada dia.</p>',
  '',
  'BoomLaLaBoom Team',
  4,
  false,
  now() - interval '23 days',
  'Musique et langage chez les enfants',
  'Music and language for kids',
  'Musica y lenguaje en ninos',
  'Comment la musique aide le langage des enfants.',
  'How music helps kids language development.',
  'Como la musica ayuda el lenguaje infantil.'
),
(
  'comptines-voitures',
  'vehicle-songs-for-kids',
  'canciones-vehiculos',
  'Chansons de voitures pour enfants',
  'Vehicle songs for kids',
  'Canciones de vehiculos',
  'Des chansons pour apprendre les vehicules et les couleurs.',
  'Songs to learn vehicles and colors.',
  'Canciones para aprender vehiculos y colores.',
  '<h2>Vehicules et sons</h2><p>Vroum, vroum pour apprendre en s amusant.</p>',
  '<h2>Vehicles and sounds</h2><p>Vroom sounds help learning with fun.</p>',
  '<h2>Vehiculos y sonidos</h2><p>Vrum ayuda a aprender jugando.</p>',
  '',
  'BoomLaLaBoom Team',
  4,
  false,
  now() - interval '24 days',
  'Chansons de voitures pour enfants',
  'Vehicle songs for kids',
  'Canciones de vehiculos para ninos',
  'Comptines pour apprendre les vehicules en musique.',
  'Songs to learn vehicles with music.',
  'Canciones para aprender vehiculos con musica.'
),
(
  'comptines-ecole',
  'back-to-school-songs',
  'canciones-escuela',
  'Chansons pour la rentree',
  'Back to school songs',
  'Canciones para la escuela',
  'Des chansons pour preparer la rentree et la routine.',
  'Songs to prepare school routines.',
  'Canciones para preparar la rutina escolar.',
  '<h2>Rassurer</h2><p>La musique aide a gerer les transitions.</p>',
  '<h2>Reassure</h2><p>Music helps manage transitions.</p>',
  '<h2>Calmar</h2><p>La musica ayuda a las transiciones.</p>',
  '',
  'BoomLaLaBoom Team',
  4,
  false,
  now() - interval '25 days',
  'Chansons pour la rentree',
  'Back to school songs',
  'Canciones para la escuela',
  'Comptines pour une rentree sereine.',
  'Songs for a calm school start.',
  'Canciones para un inicio tranquilo.'
),
(
  'chansons-saisons',
  'songs-about-seasons',
  'canciones-estaciones',
  'Chansons sur les saisons',
  'Songs about seasons',
  'Canciones sobre estaciones',
  'Des chansons pour decouvrir les saisons et la nature.',
  'Songs to discover seasons and nature.',
  'Canciones para descubrir estaciones y naturaleza.',
  '<h2>Printemps, ete, automne, hiver</h2><p>Chaque saison a sa chanson.</p>',
  '<h2>Spring, summer, fall, winter</h2><p>Each season has a song.</p>',
  '<h2>Primavera, verano, otono, invierno</h2><p>Cada estacion tiene una cancion.</p>',
  '',
  'BoomLaLaBoom Team',
  4,
  false,
  now() - interval '26 days',
  'Chansons sur les saisons',
  'Songs about seasons',
  'Canciones sobre estaciones',
  'Comptines pour apprendre les saisons en musique.',
  'Songs to learn seasons with music.',
  'Canciones para aprender estaciones con musica.'
),
(
  'comptines-corporel',
  'body-parts-songs',
  'canciones-partes-cuerpo',
  'Chansons pour apprendre le corps',
  'Body parts songs',
  'Canciones del cuerpo',
  'Apprendre les parties du corps en musique.',
  'Learn body parts with music.',
  'Aprender partes del cuerpo con musica.',
  '<h2>Jeu de gestes</h2><p>Toucher et nommer chaque partie.</p>',
  '<h2>Gesture game</h2><p>Touch and name each part.</p>',
  '<h2>Juego de gestos</h2><p>Tocar y nombrar cada parte.</p>',
  '',
  'BoomLaLaBoom Team',
  3,
  false,
  now() - interval '27 days',
  'Chansons pour apprendre le corps',
  'Body parts songs for kids',
  'Canciones del cuerpo para ninos',
  'Comptines pour apprendre le corps humain.',
  'Songs to learn body parts.',
  'Canciones para aprender partes del cuerpo.'
),
(
  'chansons-nature',
  'nature-songs-for-kids',
  'canciones-naturaleza',
  'Chansons sur la nature',
  'Nature songs for kids',
  'Canciones sobre naturaleza',
  'Des chansons pour parler des plantes et animaux.',
  'Songs about plants and animals.',
  'Canciones sobre plantas y animales.',
  '<h2>Observer</h2><p>Nommer ce que l on voit dehors.</p>',
  '<h2>Observe</h2><p>Name what you see outside.</p>',
  '<h2>Observar</h2><p>Nombrar lo que se ve afuera.</p>',
  '',
  'BoomLaLaBoom Team',
  3,
  false,
  now() - interval '28 days',
  'Chansons sur la nature',
  'Nature songs for kids',
  'Canciones sobre naturaleza',
  'Comptines pour parler de la nature.',
  'Songs to talk about nature.',
  'Canciones para hablar de naturaleza.'
),
(
  'comptines-amities',
  'friendship-songs',
  'canciones-amistad',
  'Chansons sur l amitie',
  'Friendship songs',
  'Canciones de amistad',
  'Des chansons pour parler de l amitie et du partage.',
  'Songs about friendship and sharing.',
  'Canciones sobre amistad y compartir.',
  '<h2>Partager</h2><p>Chanter ensemble pour apprendre a partager.</p>',
  '<h2>Share</h2><p>Sing together to learn sharing.</p>',
  '<h2>Compartir</h2><p>Cantar juntos para aprender a compartir.</p>',
  '',
  'BoomLaLaBoom Team',
  3,
  false,
  now() - interval '29 days',
  'Chansons sur l amitie',
  'Friendship songs for kids',
  'Canciones de amistad para ninos',
  'Comptines pour apprendre a vivre ensemble.',
  'Songs to learn living together.',
  'Canciones para aprender a convivir.'
),
(
  'comptines-famille',
  'family-songs-for-kids',
  'canciones-familia',
  'Chansons sur la famille',
  'Family songs for kids',
  'Canciones sobre la familia',
  'Des chansons pour parler de la famille et des liens.',
  'Songs about family and bonds.',
  'Canciones sobre la familia y los lazos.',
  '<h2>La famille</h2><p>Nommer les membres et leurs roles.</p>',
  '<h2>Family</h2><p>Name members and their roles.</p>',
  '<h2>Familia</h2><p>Nombrar miembros y sus roles.</p>',
  '',
  'BoomLaLaBoom Team',
  3,
  false,
  now() - interval '30 days',
  'Chansons sur la famille',
  'Family songs for kids',
  'Canciones sobre la familia para ninos',
  'Comptines pour parler de la famille.',
  'Songs to talk about family.',
  'Canciones para hablar de familia.'
);
